# Initialisation

In [1]:
import matplotlib
matplotlib.use('Qt5Agg')  # Utiliser le backend Qt5Agg pour Windows
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from scipy.optimize import curve_fit
import cv2
import numpy as np
import os
from PIL import Image
import lmfit
#import tifffile
#%matplotlib tk #pour Linux

In [2]:
import scipy.ndimage as ndimage
from sklearn.cluster import DBSCAN
import matplotlib.animation as animation


# Importer fichier

In [3]:
# path_to_tiff = os.path.join("..", "acquisition", "video_output_carac_125ms_2im_1um.tiff")
path_to_tiff = os.path.join("..", "acquisition", "essai_10um_2im_50ms.tiff")

tiff = Image.open(path_to_tiff)

# Nombre de frames pas vide

In [4]:
with Image.open(path_to_tiff) as img:
    frame_number = 0
    actual_frames = 0
    try:
        while True:
            frame_number += 1
            if np.sum(np.array(img)) != 0:
                actual_frames += 1
                
            img.seek(frame_number)
    except EOFError:
        print("All frames processed.")

actual_frames

All frames processed.


73

# 1re frame

**Le nombre de frames ignorés n'est pas pris en compte**

In [5]:
frame_index = 0
first_frame = 0
tiff.seek(frame_index)
original_image = np.array(tiff)

while np.sum(original_image) == 0:
    frame_index += 1
    tiff.seek(frame_index)
    original_image = np.array(tiff)
    first_frame += 1
    print(frame_index)




# Traitement d'image

In [6]:
clahe = cv2.createCLAHE(clipLimit=10.0, tileGridSize=(30, 30))
preprocessed = clahe.apply(original_image)

blurred = cv2.medianBlur(preprocessed, 115)
preprocessed2 = cv2.subtract(preprocessed, blurred)

# Apply Non-Local Means Denoising
img = cv2.fastNlMeansDenoising(preprocessed2, None, 15, 7, 41)


# Sélection du point à tracker

In [7]:
def crop(img, x, y, crop_size_x, crop_size_y):
    x_start = int(x - crop_size_x // 2)
    x_end = int(x + crop_size_x // 2)
    y_start = int(y - crop_size_y // 2)
    y_end = int(y + crop_size_y // 2)

    return img[y_start:y_end, x_start:x_end]

In [8]:
# Display the image and let the user select a point interactively
fig, ax = plt.subplots()
ax.imshow(img, origin='lower', cmap='gray')  # Use 'gray' for better visibility of grayscale images
plt.title(f"Frame {frame_index}: Select a point")
plt.xlabel(f'Position horizontale (pixel)')
plt.ylabel(f'Position verticale (pixel)')

# Ask for a point to be selected
print("Please click on the point you want to select.")
x, y = plt.ginput(1)[0]  # This will get the coordinates of the clicked point
print(f"Selected point: ({x}, {y})")
plt.close()

crop_sze = crop_sze_x = crop_sze_y = 50

Please click on the point you want to select.
Selected point: (1105.2142857142858, 575.7337662337662)


Debogueur

In [9]:
def visionneur(frame, titre):
    plt.figure(figsize=(10, 5))
    plt.clf() 
    plt.imshow(frame, origin='lower', cmap='gray')
    plt.title(titre)
    plt.colorbar()  
    plt.show()

# Fit gaussien sur le point sélectionné

In [10]:
def prepare_data(x, y, z):
    return (x.flatten(), y.flatten()), z.flatten()

In [11]:
def gaussian_2d(xy, amplitude, x0, y0, sigma_x, sigma_y, offset):
    x, y = xy
    a = 1 / (2 * sigma_x**2)
    b = 1 / (2 * sigma_y**2)
    return offset + amplitude * np.exp(- (a * (x - x0)**2 + b * (y - y0)**2))

In [12]:
def localisateur_gaussien(intensity_grid, centre):
    x = np.arange(intensity_grid.shape[1])
    y = np.arange(intensity_grid.shape[0])
    X, Y = np.meshgrid(x, y)

    # Préparer les données pour le fit
    (xdata, ydata), zdata = prepare_data(X, Y, intensity_grid)
    model = lmfit.Model(gaussian_2d)
    max_idx = np.unravel_index(np.argmax(intensity_grid), intensity_grid.shape)
    initial_x0 = x[max_idx[1]]
    initial_y0 = y[max_idx[0]]

    # Définir les paramètres du modèle
    params = model.make_params(
        amplitude=np.max(intensity_grid),
        x0=initial_x0,
        y0=initial_y0,
        sigma_x=1,
        sigma_y=1,
        offset=2
    )

    # Ajouter des bornes sur les paramètres x0 et y0
    params['x0'].min = 0    # Limite inférieure pour x0
    params['x0'].max = intensity_grid.shape[1] - 1  # Limite supérieure pour x0
    params['y0'].min = 0    # Limite inférieure pour y0
    params['y0'].max = intensity_grid.shape[0] - 1  # Limite supérieure pour y0

    # Ajouter des bornes sur les paramètres sigma
    params['sigma_x'].min = 1  # Limite inférieure de sigma_x
    params['sigma_x'].max = 20 # Limite supérieure de sigma_x
    params['sigma_y'].min = 1  # Limite inférieure de sigma_y
    params['sigma_y'].max = 20 # Limite supérieure de sigma_y

    # Effectuer l'ajustement
    result = model.fit(zdata, params, xy=(xdata, ydata))
    
    x_position = result.params['x0'].value + centre[0] - crop_sze_x/4
    y_position = result.params['y0'].value + centre[1] - crop_sze_y/4

    return [x_position, y_position], result.params['sigma_x'].value, result.params['sigma_y'].value

# Process d'image (enlever le bruit)

**semble faire du trouble**

In [13]:
def denoise(image):
    clahe = cv2.createCLAHE(clipLimit=10.0, tileGridSize=(30, 30))
    preprocessed = clahe.apply(image)
    
    blurred = cv2.medianBlur(preprocessed, 115)
    preprocessed2 = cv2.subtract(preprocessed, blurred)
    
    return cv2.fastNlMeansDenoising(preprocessed2, None, 15, 7, 41)

# Identifier la particule et donner sa nouvelle position

In [14]:
def is_within_bounds(position):
    """
    Vérifie si la position est à l'intérieur des limites du cadre (100 à 1300 en x et 100 à 980 en y).
    """
    x, y = position

    # Définir les bornes du cadre
    x_min, x_max = 100, 1300
    y_min, y_max = 100, 980

    # Vérifier si la position est dans les bornes du cadre
    if x_min <= x <= x_max and y_min <= y <= y_max:
        return True
    else:
        return False


In [15]:
def empreinte_digitale(image, threshold=16, eps=3, min_samples=1):
    # 1. Observer chaque particule approximativement
    #neighborhood_size = 3  
    #local_max = ndimage.maximum_filter(image, size=neighborhood_size)
    visionneur(image, f'particule choisie')

    maxima = (image > threshold)
    
    coordinates = np.column_stack(np.where(maxima))  
    if coordinates.shape[0] == 0:
        print("Aucune particule détectée.")
        return [], image

    dbscan = DBSCAN(eps=eps, min_samples=min_samples)
    labels = dbscan.fit_predict(coordinates)
    unique_labels = np.unique(labels)
    size=0

    # 2. Déterminer l'empreinte digitale de notre particule
    for label in unique_labels:
        if label != -1:  # -1 correspond au bruit dans DBSCAN
            cluster_points = coordinates[labels == label]
            plt.scatter(cluster_points[:, 1], cluster_points[:, 0], label=f'Particule {label}')

            if cluster_points.shape[0]>size:
                size = cluster_points.shape[0]
                luminosity = np.mean(image[cluster_points[:, 0], cluster_points[:, 1]])

    seuil=np.max(image)*0.5
    print(seuil)
    # 3. Afficher les résultats et filtrer les particules selon leur taille et luminosité
    plt.imshow(image, origin='lower', cmap='gray')
    plt.title(f"Empreinte digitale de la particule, lum={luminosity} et taille={size}")
    plt.legend()
    plt.colorbar()  
    plt.show()

    return size, luminosity, seuil

In [16]:
def detect_nbre_particles(image, threshold, eps=5, min_samples=1):
    # 1. Appliquer un filtre de voisinage pour détecter les maxima locaux
    neighborhood_size = 3  # Taille du voisinage pour détecter les maxima locaux
    local_max = ndimage.maximum_filter(image, size=neighborhood_size)
    # 2. Comparer l'image originale et les maxima locaux pour identifier les vrais maxima
    maxima = (image == local_max) & (image > threshold)

    # 3. Extraire les coordonnées des maxima (particules)
    coordinates = np.column_stack(np.where(maxima))  # Extraire les indices des pixels maximaux
    if coordinates.shape[0] == 0:
        print("Aucune particule détectée.")
        visionneur(image, f'détection du nombre de particules')

        return [], image

    # 4. Appliquer DBSCAN pour regrouper les particules proches (cluster les maxima détectés)
    dbscan = DBSCAN(eps=eps, min_samples=min_samples)
    labels = dbscan.fit_predict(coordinates)

    #5. Déterminer le nombre de particules
    unique_labels = np.unique(labels)
    nb_particules = len(unique_labels)
        
    # 6. Afficher les résultats et filtrer les particules selon leur taille et luminosité
    # plt.imshow(image, origin='lower', cmap='gray')
    # plt.title("Détection des particules")
    
    positions=[]
    for label in unique_labels:
        if label != -1:  # -1 correspond au bruit dans DBSCAN
            cluster_points = coordinates[labels == label]
            #plt.scatter(cluster_points[:, 1], cluster_points[:, 0], label=f'Particule {label}')
        positions.append((np.mean(cluster_points[:, 1]), np.mean(cluster_points[:, 0])))
        

    # plt.colorbar()  
    # plt.legend()
    # plt.show()

    # Retourner les coordonnées des particules filtrées
    return nb_particules, positions

In [17]:
def identificateur_particles(image, ref_size, ref_luminosity, threshold=25, eps=5, min_samples=1):
    # 1. Obtenir le plus d'info sur la particule
    maxima = (image > threshold)
    
    coordinates = np.column_stack(np.where(maxima))  
    if coordinates.shape[0] == 0:
        print("Mauvais re-crop empêche identification de la particule.")
        return [], image

    dbscan = DBSCAN(eps=eps, min_samples=min_samples)
    labels = dbscan.fit_predict(coordinates)
    unique_labels = np.unique(labels)

    # 2. Parcourir chaque particule et identifier laquelle est celle qu'on suit
    distances = []
    position_particules = []

    for label in unique_labels:
        if label != -1:  # -1 correspond au bruit dans DBSCAN
            cluster_points = coordinates[labels == label]
            
            size = cluster_points.shape[0]
            luminosity = np.mean(image[cluster_points[:, 0], cluster_points[:, 1]])
            size_distance = abs(size - ref_size)  
            luminosity_distance = abs(luminosity - ref_luminosity)  
            combined_distance = size_distance + luminosity_distance
            distances.append(combined_distance)
            position_particules.append((np.mean(cluster_points[:, 1]), np.mean(cluster_points[:, 0])))

    ecart = np.min(distances)
    position_best_particle = position_particules[np.argmin(distances)]  
    print(f'ecrat: {ecart}')
    # 3. Afficher les résultats et filtrer les particules selon leur taille et luminosité
    # plt.imshow(image, origin='lower', cmap='gray')
    # plt.title("Détection des particules")
    # plt.scatter(position_best_particle[0], position_best_particle[1], color='r', label=f'Particule sélectionnée')
    # plt.legend()
    # plt.colorbar()  
    # plt.show()

    return position_best_particle, ecart

# Faire le crop et fit

In [18]:
def particle_tracker_simple(image, x, y):
    image = denoise(image)

    cropped_img = crop(image, x, y, crop_sze_x, crop_sze_y)
    
    #Gérer plus qu'une particule
    cropped_img = np.array(cropped_img)
    max_index = np.argmax(cropped_img)
    max_coords = np.unravel_index(max_index, cropped_img.shape)

    nouveau_x = x - crop_sze_x // 2 + max_coords[1]
    nouveau_y = y - crop_sze_y // 2 + max_coords[0]
    
    second_crop = crop(image, nouveau_x, nouveau_y, crop_sze_x, crop_sze_y)    # Re-crop autour d'une seule particule

    result_fit = localisateur_gaussien(second_crop, [nouveau_x, nouveau_y])

    x_new, y_new = result_fit[0][0], result_fit[0][1]

    return [result_fit, cropped_img, (x_new, y_new), (result_fit[1], result_fit[2])]

In [19]:
#Placés ici pour pouvoir y faire référence dans particule_tracker
position_list=[[x,y]]
sigma_list = []
crop_frames = []
big_frames = []

In [20]:
def particle_tracker(imge, x, y, taille_initiale, luminosité_initiale, seuil):
    # 1. Ce qu'on voit près de l'ancienne position
    image = denoise(imge)

    cropped_img = crop(image, x, y, crop_sze_x, crop_sze_y)
    
    # 2. Déterminer combien il y a de particules et laquelle est la notre
    # Utiliser une reconnaissance de particules et si plus qu'une, alors clic pour choisir
    nb_part, coordonnées = detect_nbre_particles(cropped_img, seuil)
    #print(f'coordonnées des {nb_part} particules:{coordonnées}')

    if (nb_part == 0) or (nb_part == []):
        # Display the image and let the user select a point interactively
        fig, ax = plt.subplots()
        ax.imshow(denoise(img), origin='lower', cmap='gray') 
        plt.title(f"Frame {len(position_list)-1}: Select a point")

        # Ajouter une croix rouge à la position donnée
        cx, cy = position_list[len(position_list)-1]
        ax.plot(cx, cy, 'rx', markersize=10) 
        
        # Afficher l'image et demander à l'utilisateur de cliquer
        print("Please click on the point you want to select.")
        nouveau_x, nouveau_y = plt.ginput(1)[0]  # Attente du clic de l'utilisateur (1 point)
        print(f"Selected point: ({nouveau_x}, {nouveau_y})")
        
        # Fermer l'affichage après sélection
        plt.close()
    elif nb_part > 1:
        imperfections, emplacements = [] , []
        for num_particule in range(nb_part):
            x_identifier=x - crop_sze_x // 2 + coordonnées[num_particule][0]
            y_identifier=y - crop_sze_y // 2 + coordonnées[num_particule][1]
            crop_pour_identifier = crop(image, x_identifier, y_identifier, crop_sze_x//2, crop_sze_y//2)
            emplacement, ecart = identificateur_particles(crop_pour_identifier, taille_initiale, luminosité_initiale, seuil)
            imperfections.append(ecart)
            emplacements.append(emplacement)
        qualité = np.min(imperfections)
        print(f'écart:{qualité}')
        max_coords = emplacements[np.argmin(imperfections)]  
        nouveau_x = x_identifier - crop_sze_x // 4 + max_coords[0]
        nouveau_y = y_identifier - crop_sze_y // 4 + max_coords[1]
    else:
        cropped_img = np.array(cropped_img)
        max_index = np.argmax(cropped_img)
        max_coords = np.unravel_index(max_index, cropped_img.shape)

        nouveau_x = x - crop_sze_x // 2 + max_coords[1] #Oui c'est inversé à cause du unravel juste avant
        nouveau_y = y - crop_sze_y // 2 + max_coords[0]

    # Vérification s'il fout le camp 
    if np.sqrt((position_list[-1][0]-nouveau_x)**2+(position_list[-1][1]-nouveau_y)**2)>50:
        # Display the image and let the user select a point interactively
        fig, ax = plt.subplots()
        ax.imshow(denoise(img), origin='lower', cmap='gray') 
        plt.title(f"Frame {len(position_list)-1}: Problème d'identification, select a point")

        print('problème d''identification')
        # Ajouter une croix rouge à la position donnée
        cx, cy = position_list[-1]
        ax.plot(cx, cy, 'rx', markersize=10, label=f'Position estimée') 
        plt.legend()
        # Afficher l'image et demander à l'utilisateur de cliquer
        print("Please click on the point you want to select.")
        nouveau_x, nouveau_y = plt.ginput(1)[0]  # Attente du clic de l'utilisateur (1 point)
        print(f"Selected point: ({nouveau_x}, {nouveau_y})")
        
        # Fermer l'affichage après sélection
        plt.close()

    # 3. Crop atour de notre particule et fit dessus
    second_crop = crop(image, nouveau_x, nouveau_y, crop_sze_x//2, crop_sze_y//2)    # Re-crop autour d'une seule particule


    result_fit = localisateur_gaussien(second_crop, [nouveau_x, nouveau_y])

    x_new, y_new = result_fit[0][0], result_fit[0][1]

    # Affiche l'accord entre le fit gaussien et le blob (pour comparer)
    # if len(position_list)==5:    
    #     x_list, y_list = zip(*position_list)
    #     x_list = list(x_list)  # Convertir en liste
    #     y_list = list(y_list)  # Convertir en liste        
    #     x_list.append(x_new)
    #     y_list.append(y_new)   
    #     plt.imshow(image, origin='lower', cmap='gray')#, extent=[x_position.min(), x_position.max(), y_position.min(), y_position.max()])
    #     plt.title("tracking de la particule")
    #     plt.scatter(x_list, y_list, color='b', label=f'Positions précédentes')
    #     plt.scatter(x_new, y_new, color='r', label=f'Position actuelle estimée par fit gaussien')
    #     plt.plot(x_list, y_list, color='b', linestyle='-', linewidth=1)
    #     plt.xlabel('Position horizontale (nombre de pixel)')
    #     plt.ylabel('Position veticale (nombre de pixel)')
    #     plt.legend()
    #     plt.show()

    return [result_fit, second_crop, (x_new, y_new), (result_fit[1], result_fit[2])]

# Main loop

In [21]:
taille_initiale, luminosité_initiale, seuil = empreinte_digitale(crop(img,x,y,35,35))
print(f'position initiale: {position_list}')

for i in range(first_frame+1,actual_frames):
    tiff.seek(i)
    if np.sum(np.array(tiff))==0:
        #print(f'x={x}')
        position_list.append(np.array([np.nan,np.nan]))
        sigma_list.append(np.array([np.nan,np.nan]))
        print(f'frames vide:{i}')
    else:
        #print(f'x={x}')
        data = particle_tracker(img, x, y, taille_initiale, luminosité_initiale, seuil)
        position_list.append(data[2])
        # x,y = position_list[i-first_frame+1] Valeur de First frame n'a pas d'impact apparemment
        x,y = position_list[i]
        sigma_list.append(data[3])
        tiff.seek(i)
        img = np.array(tiff)
        big_frames.append(img)
        # plt.imshow(img)
        # plt.show()
        crop_frames.append(data[1])
        if is_within_bounds(position_list[-1]):
            pass
        else:
            break
    print(f'liste des positions frame {i}:{position_list}')
    
    
position_list=position_list[1:] #On ignore le premier point cliqué car incertitude non définie

92.0
position initiale: [[1105.2142857142858, 575.7337662337662]]
liste des positions frame 1:[[1105.2142857142858, 575.7337662337662], (1104.3706477248586, 570.3208167865637)]
liste des positions frame 2:[[1105.2142857142858, 575.7337662337662], (1104.3706477248586, 570.3208167865637), (1106.0442057055843, 565.3697396322322)]
liste des positions frame 3:[[1105.2142857142858, 575.7337662337662], (1104.3706477248586, 570.3208167865637), (1106.0442057055843, 565.3697396322322), (1106.493370165924, 561.003292216581)]
liste des positions frame 4:[[1105.2142857142858, 575.7337662337662], (1104.3706477248586, 570.3208167865637), (1106.0442057055843, 565.3697396322322), (1106.493370165924, 561.003292216581), (1107.2593896608923, 556.1733260857792)]
liste des positions frame 5:[[1105.2142857142858, 575.7337662337662], (1104.3706477248586, 570.3208167865637), (1106.0442057055843, 565.3697396322322), (1106.493370165924, 561.003292216581), (1107.2593896608923, 556.1733260857792), (1108.7922644537

In [22]:
pixel_size = 3.45 # Taille absolue
f2 = 150  # Focale de L2
M_theo = 20  # Magnification of the objective
pxl = pixel_size / (f2 * M_theo / 160)  # Pixel size in um dans le plan de la particule

sigma_arr=np.array(sigma_list)* pxl * 10**(-6)
position_arr=np.array(position_list)* pxl * 10**(-6)
print(position_arr)

[[2.03204199e-04 1.04939030e-04]
 [2.03512134e-04 1.04028032e-04]
 [2.03594780e-04 1.03224606e-04]
 [2.03735728e-04 1.02335892e-04]
 [2.04017777e-04 1.01465842e-04]
 [2.03780647e-04 1.00555681e-04]
 [2.03565617e-04 9.87814046e-05]
 [2.04074093e-04 9.85768645e-05]
 [2.04057171e-04 9.74900635e-05]
 [2.07660470e-04 1.03745714e-04]
 [2.04282312e-04 1.00838316e-04]
 [2.04206870e-04 9.51577130e-05]
 [           nan            nan]
 [           nan            nan]
 [2.04495848e-04 9.41757847e-05]
 [2.05174370e-04 9.17198607e-05]
 [2.05716945e-04 9.17312893e-05]
 [2.06121398e-04 9.25292470e-05]
 [2.05939033e-04 9.14271507e-05]
 [2.06059581e-04 8.75803442e-05]
 [2.06608524e-04 8.68556688e-05]
 [2.06750423e-04 8.61731986e-05]
 [2.06737657e-04 8.56564003e-05]
 [2.06990297e-04 8.46917047e-05]
 [2.07602680e-04 8.69807631e-05]
 [2.07157486e-04 8.22790239e-05]
 [2.07047392e-04 8.10039959e-05]
 [2.07124838e-04 8.03112541e-05]
 [2.07262916e-04 7.97052047e-05]
 [2.07371710e-04 7.90859784e-05]
 [2.074887

In [23]:
def calculate_msd_with_uncertainty(position_arr, delta_x, delta_y):
    """
    Calcule les MSD avec propagation des incertitudes analytiques.
    """

    msd = []
    uncertainties = []
    for d in range(1, len(position_arr)):
        diff_pairs = np.zeros_like(position_arr[d:])
        dx = np.zeros_like(delta_x[d:])
        dy = np.zeros_like(delta_y[d:])

        # Masque pour détecter les NaN
        nan_mask_pos = np.isnan(position_arr[d:]) | np.isnan(position_arr[:-d])
        nan_mask_delta = np.isnan(delta_x[d:]) | np.isnan(delta_x[:-d])
        
        # Calculer les différences uniquement où nan_mask est False
        valid_mask_pos = ~nan_mask_pos.any(axis=1)  # Inverser le masque pour obtenir les position_arr valides
        valid_mask_delta = ~nan_mask_delta

        diff_pairs[valid_mask_pos] = position_arr[d:][valid_mask_pos, :] - position_arr[:-d][valid_mask_pos, :]

        distances_squared = np.sum(diff_pairs**2, axis=1)
        msd.append(np.mean(distances_squared))  

        dx[valid_mask_delta] = delta_x[d:][valid_mask_delta] + delta_x[:-d][valid_mask_delta]
        dy[valid_mask_delta] = delta_y[d:][valid_mask_delta] + delta_y[:-d][valid_mask_delta]

        term_x = 2 * (diff_pairs[:, 0]**2) * (dx**2)
        term_y = 2 * (diff_pairs[:, 1]**2) * (dy**2)
        
        # Propagation des incertitudes
        total_uncertainty = np.mean(term_x + term_y)
        uncertainties.append(np.sqrt(total_uncertainty))

    return np.array(msd), np.array(uncertainties)

calculate_msd_with_uncertainty(position_arr, sigma_arr[:, 0], sigma_arr[:, 1])

(array([3.02227808e-12, 6.13334865e-12, 8.82964032e-12, 1.46553849e-11,
        2.33009197e-11, 3.15274936e-11, 4.06275593e-11, 5.18817713e-11,
        6.58371059e-11, 8.18832037e-11, 1.00127118e-10, 1.17650293e-10,
        1.37461029e-10, 1.60162622e-10, 1.83499466e-10, 2.09317389e-10,
        2.35924652e-10, 2.64807638e-10, 2.95480597e-10, 3.25016323e-10,
        3.54968108e-10, 3.87617423e-10, 4.22729325e-10, 4.60245280e-10,
        5.01056625e-10, 5.40057728e-10, 5.79197925e-10, 6.19976299e-10,
        6.63406312e-10, 7.09185542e-10, 7.57328464e-10, 8.07223002e-10,
        8.59070310e-10, 9.09820850e-10, 9.60860467e-10, 1.01451590e-09,
        1.07081876e-09, 1.12899993e-09, 1.18813797e-09, 1.24563967e-09,
        1.30516880e-09, 1.36574657e-09, 1.42812402e-09, 1.49290039e-09,
        1.56042282e-09, 1.62937637e-09, 1.69826209e-09, 1.75426409e-09,
        1.82363114e-09, 1.89465970e-09, 1.96701355e-09, 2.03746711e-09,
        2.11264921e-09, 2.17700794e-09, 2.23628139e-09, 2.302266

# Résultats

In [24]:
# Assuming msd_values is the result of your MSD calculation
msd_values, uncertainties = calculate_msd_with_uncertainty(position_arr, sigma_arr[:, 0], sigma_arr[:, 1])
print('coucou')
# Time intervals for the x-axis (assuming a uniform time step)
time_intervals = np.arange(1, len(msd_values) + 1) * 0.5

# Plotting the MSD
plt.figure(figsize=(8, 6))
plt.errorbar(time_intervals, msd_values, yerr=uncertainties, fmt='o', label='MSD', color='blue')

# Customize the plot
plt.title("MSD en fonction de l'intervalle de temps")
plt.xlabel("Intervalle de temps")
plt.ylabel("MSD")
plt.grid(True)
plt.legend()

# Show the plot
plt.show()

coucou


In [25]:
# Fonction quadratique pour l'ajustement
def quadratic(x, a, b, c):
    return a * x**2 + b * x + c

# Assuming msd_values is the result of your MSD calculation
msd_values, uncertainties = calculate_msd_with_uncertainty(position_arr, sigma_arr[:, 0], sigma_arr[:, 1])

cropped_msd = msd_values[:5]
cropped_inc = uncertainties[:5]

# Time intervals for the x-axis (assuming a uniform time step)
time_intervals = np.arange(1, len(cropped_msd) + 1)

# Perform a quadratic fit using curve_fit, which gives both coefficients and covariance matrix
popt, pcov = curve_fit(quadratic, time_intervals, cropped_msd, sigma=cropped_inc)

# popt contains the optimal coefficients
coeffs = popt

# pcov is the covariance matrix, which we can use to compute uncertainties
coeff_uncertainties = np.sqrt(np.diag(pcov))  # Incertitudes sur les coefficients sont les éléments diagonaux

# Affichage des coefficients séparément
print("Coefficients du polynôme ajusté :")
print(coeffs)

# Affichage de la matrice de covariance séparément
print("Matrice de covariance des coefficients :")
print(pcov)

# Création de la fonction quadratique de l'ajustement
quadratic_fit = np.poly1d(coeffs)

# Génération des valeurs ajustées pour afficher la courbe
fitted_msd = quadratic_fit(time_intervals)

# Affichage du MSD avec les barres d'erreur
plt.figure(figsize=(8, 6))
plt.errorbar(time_intervals, cropped_msd, yerr=cropped_inc, fmt='o', label='MSD', color='blue')
plt.plot(time_intervals, fitted_msd, label='Quadratic Fit', color='red', linestyle='--')

# Personnalisation du graphique
plt.title("MSD en fonction de l'intervalle de temps")
plt.xlabel("Intervalle de temps")
plt.ylabel("MSD")
plt.grid(True)
plt.legend()

# Afficher le graphique
plt.show()

# Affichage des incertitudes sur les coefficients
print(f"Incertitudes sur les coefficients : {coeff_uncertainties}")

# Calcul du coefficient de diffusion et de la taille de la particule
r = (4 * 1.38 * 10**(-23) * 300 / (6 * np.pi * 10**(-3) * coeffs[1]))  # Coefficient de diffusion
r_uncertainty = (4 * 1.38 * 10**(-23) * 300 * coeff_uncertainties[1] / (6 * np.pi * 10**(-3) * (coeffs[1])**2))  # Coefficient de diffusion

# Affichage de la taille de la particule avec incertitude
print(f"Taille de la particule (m): {r:.2e} m, avec une incertitude : {r_uncertainty:.2e}")


Coefficients du polynôme ajusté :
[ 8.60433091e-13 -2.90375107e-13  2.57546918e-12]
Matrice de covariance des coefficients :
[[ 5.47489228e-26 -2.86605512e-25  2.71260409e-25]
 [-2.86605512e-25  1.57380137e-24 -1.56290446e-24]
 [ 2.71260409e-25 -1.56290446e-24  1.72805668e-24]]
Incertitudes sur les coefficients : [2.33984877e-13 1.25451240e-12 1.31455570e-12]
Taille de la particule (m): -3.03e-06 m, avec une incertitude : 1.31e-05


In [26]:
x_plt, y_plt = zip(*position_list)
# Create the plot
plt.figure(figsize=(10, 8))  # Optional: Adjust the figure size
plt.plot(x_plt, y_plt, marker='o', linestyle='-', color='b', label='Connected Points')

# Inverser l'axe Y
plt.gca().invert_yaxis()

# Set grid limits to match the 1440x1080 grid
plt.xlim(0, 1440)
plt.ylim(0, 1080)

# Add labels and title
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('2D Connected Points Plot')
plt.legend()

# Optional: Add grid lines
plt.grid(True)

# Afficher le graphique
plt.show()

## anim toutes les particules

In [27]:
fig, ax = plt.subplots()
img = ax.imshow(big_frames[0], origin='lower', cmap='gray', animated=True)


# Update function
def update(frame):
    img.set_array(frame)
    return img,
    
ani = animation.FuncAnimation(fig, update, frames=big_frames, interval=50, blit=True)
plt.show()

## anim crop

In [28]:
fig, ax = plt.subplots()
img = ax.imshow(crop_frames[0], origin='lower', cmap='gray', animated=True)


def update(frame):
    img.set_array(frame)
    return img,
    
ani = animation.FuncAnimation(fig, update, frames=crop_frames, interval=50, blit=True)
plt.show()

In [29]:
# Exemple de grid setup (comme précédemment)
x = np.linspace(0, 1440)  # ajusté pour créer une grille plus fine
y = np.linspace(0, 1080)
X, Y = np.meshgrid(x, y)

# Créer des images (frames)
frames = []
for i in range(len(big_frames)):
    frame = big_frames[i]
    posi = position_list[i]
    frames.append([frame, posi])

# Paramètres de la figure
fig, ax = plt.subplots()
ax.set_title("Mouvement brownien de la particule")
ax.set_xlim(0, 1440)
ax.set_ylim(0, 1080)
ax.set_aspect('equal')
plt.xlabel('Position horizontale (en pixel)')
plt.ylabel('Position verticale (en pixel)')

# Initialisation de l'image
img = ax.imshow(big_frames[0], cmap='gray', animated=True)
cb = plt.colorbar(img, ax=ax, label='Intensité')

# Utiliser une liste pour stocker les indices à supprimer
indices_a_supprimer = []

# Identifiant des indices à supprimer
for index in range(len(position_list)):
    if np.isnan(position_list[index][0]):  # Vérifier si la première valeur de la position est NaN
        indices_a_supprimer.append(index)

# Supprimer les éléments de position_list et frames dans l'ordre inverse pour éviter de perturber l'indice
for index in reversed(indices_a_supprimer):
    position_list.pop(index)
    frames.pop(index)

# Fonction de mise à jour
def update(frame):
    img.set_array(frame[0])
    pos=frame[1]
    ax.scatter(pos[0], pos[1], color='r', s=2)  # Point blanc de taille 50
    return img,

# Choisir le writer FFMpeg
writer = animation.FFMpegWriter(fps=5, metadata=dict(artist='Me'), bitrate=1800)

# Animation
ani = animation.FuncAnimation(fig, update, frames=frames, interval=50, blit=True)

# Sauvegarder l'animation en .mp4
ani.save("particle_brownian_motion.mp4", writer=writer)

# Afficher la vidéo
plt.show()

# Vérification : Si la vidéo est correctement enregistrée
print("Vidéo enregistrée sous 'particle_brownian_motion.mp4'.")


Vidéo enregistrée sous 'particle_brownian_motion.mp4'.
